name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # chạy mỗi 6 tiếng
  workflow_dispatch:

permissions:
  contents: write   # cho phép ghi vào repo

jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TOTAL: "False"
