name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 */6 * * *' # chạy mỗi 6 tiếng
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          DEBUG_LOGGING: "True"
